spring:
  application:
    name: config-client-2
  config:
    import: configserver:http://localhost:8888
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: busrefresh,busenv,refresh,health,info
  endpoint:
    health:
      show-details: always
